version: '3.8'

services:
  app:
    build: .
    container_name: iniciando-django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: iniciando-django-db
    tty: true
    environment:
      - POSTGRES_DB=iniciando_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: iniciando-django-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db  

volumes:
  pgdata:
