# Generated by Django 3.0.7 on 2020-06-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='category teste', max_length=255),
            preserve_default=False,
        ),
    ]
